### PR TITLE
Add user management

### LINKED ISSUE #85: user management
we need a user management like in spacialist

### PR DESCRIPTION
**Pull request by v1r0x**
Fix #85, #86 

This PR adds user management based on spacialist's user management. To test this branch please run `composer udpate`. A default admin account is created, if not created yet. To also add a guest account you have to exec (see https://github.com/eScienceCenter/Spacialist/pull/169):
```bash
composer dump-autoload
php artisan db:seed --class=GuestUserSeeder
```

It also adds basic permission checks. The UI should only display methods/actions accessable by the user. The master tree can still be modified by a user (with given permission of course). We should think of a way how to disable modifications in the master tree (relations, labels and drag&drop). Feel free to merge if this is good enough for now or add your requests. @eScienceCenter/spacialists

### CODE REVIEW

**Comment by v1r0x** [comment]
ThesauRex has no l10n support. But yes, the translation keys from Spacialist should be replaced with the english l10n version. Is beside that everything as expected?

**Comment by derntl** [comment]
What do you mean with no l10n support? In my browser the GUI looks like this:

image

**Comment by derntl** [comment]
... and no, I cannot even log in. When I enter user and pw, I get

```
Error: modalFactory.errorModal is not a function
setAuthHeader/<.responseError@http://localhost/spacialist/thesaurex/app.js:299:25
```

maybe I do not have an account yet? Can you make me one then?

**Comment by v1r0x** [comment]
> What do you mean with no l10n support? In my browser the GUI looks like this:

We decided that we do not need l10n support for thesaurex. You just see the l10n keys, because I forgot to replace them with the actual text.

> maybe I do not have an account yet? Can you make me one then?

The internal thesaurex version only has the default admin and guest account. You could login as admin and create a new account by yourself (or simply use the admin account).

**Pull request merged**
