### PR TITLE
fix wrong index in relations

### LINKED ISSUE #37: links to broader and narrower concepts can't be solved
After selecting a concept its relations and links to narrower and broader ceoncepts can't be solved via the X-button on the right side. So right now there is no possibility to remove a relation.

### PR DESCRIPTION
**Pull request by v1r0x**
fix #37 

Please review @eScienceCenter/spacialists

### CODE REVIEW

**Comment by v1r0x** [comment]
> this does not seem to solve issue #37

That is not correct. It actually does solve #37, but the user has to reload the page :stuck_out_tongue: 

> when I remove a narrower concept, it does not disappear from the tree. after refresh it is shown as top level concept in the tree.

It's the intended behaviour that it stays in the tree as top concept. Will try to fix this, that the user gets the correct feedback without reloading the page

> also the list of concepts shows duplicates based on all available labels

You refer to the "narrower concepts" tab and this?
```
Kleinfund
http://thesaurus.archeoinf.de/MeineAnpassung/false_109
item find
http://thesaurus.archeoinf.de/MeineAnpassung/false_109
Sammelfund
http://thesaurus.archeoinf.de/MeineAnpassung/false_110
Sammelfund
http://thesaurus.archeoinf.de/MeineAnpassung/false_110
Streufund
http://thesaurus.archeoinf.de/organization#streufund
Streufund
http://thesaurus.archeoinf.de/organization#streufund 
```

**Comment by derntl** [comment]
Can it be done without needing to refresh the page?

**Comment by v1r0x** [comment]
Should be fixed now. Narrower/Broader concepts should only get displayed in one language. Duplicated concepts as `Streufund` and `Sammelfund` in my comment above are due to a bug in an earlier commit. There are two entries in the database. @derntl

**Comment by derntl** [comment]
It appears the item in the tree is removed based on the position of the item in the "Narrower concepts" list. However the list and the tree do not always have the same sorting (why by the way?). For example, go to Facetten > Flora and click Bäume und Sträucher. Delete the first one in the narrower concepts list ("Tamariske"). In the tree, "Ahorn" is deleted, since it is the first one!

**Comment by v1r0x** [comment]
I missed the fact that I had two different arrays. Now we compare the ID of the removed item with the IDs of the array in the tree and remove the element at the index which matches the ID.

**Comment by derntl** [comment]
🎱

**Pull request merged**
