### PR TITLE
Fix drag and drop

### LINKED ISSUE #36: no savings after drag and drop
concepts moves via drag and drop will not be saved in the new location after refreshing the page

### PR DESCRIPTION
**Pull request by v1r0x**
Fix #36 

This should fix the buggy drag and drop-functionality. Please review @eScienceCenter/spacialists

### CODE REVIEW

**Comment by v1r0x** [comment]
The new commit should fix the error. There are some other errors, but at least some of them are covered in other PRs/issues. Thus I'd recommend to merge this one (of course only if d&d works) and fix the other bugs in new/existing PRs and issues.

Please test again @derntl

**Comment by derntl** [comment]
Drag and drop works now without an API error but when dragging a concept its subconcepts are gone after reload

**Comment by v1r0x** [comment]
This has been fixed in #48

**Comment by derntl** [comment]
💥

**Pull request merged**
